### ISSUE TITLE
You can shoot through walls.

### ISSUE THREAD

**Issue by QazCetelic** [aehmttw/Tanks#13]
I just noticed that it's possible to shoot through walls. I'm guessing this is a bug and isn't supposed to be possible.

https://user-images.githubusercontent.com/51381523/149730234-9e763613-fa2f-41af-bcce-21f2f50588b5.mp4

**Comment by aehmttw** [comment]
This actually works as intended, it can allow for quite interesting strategy and level design :)

(Enemies can shoot through corners too, you can see this with the green tanks on one of the levels in the classic crusade)
