### ISSUE TITLE
No Linux Support On Steam

### ISSUE THREAD

**Issue by The-Emil** [aehmttw/Tanks#21]
Being a Java program, it should be compatible with Linux on Steam.

NOTE: using Proton the program works as expected without any notable performance issues.

**Comment by aehmttw** [comment]
The JAR file (which you can obtain from the README) should work on Linux natively. The only thing holding me back from a native Linux Steam version is a lack of devices to test on as of right now that run Linux. I would need to redistribute a Linux Java executable with the JAR file on Linux for it to work. I do eventually want to look into native support though. 

Also, I believe that if you add the Java executable to Steam and tell it to run Tanks using a launch argument, you can launch it from there too, but it's a bit weird.

**Comment by The-Emil** [comment]
Yes those are good solutions, it's no real issue.
Can I recommend a Linux VM or WSL? These may help.
