### ISSUE TITLE
Cannot edit Tanks Tread Colour and Turret Colour Separatly

### ISSUE THREAD

**Issue by ghostlypi** [aehmttw/Tanks#23]
[https://drive.google.com/file/d/1q1TtT-E8NF7x801iNdjcTwiPP4zfRe_9/view?usp=sharing](https://drive.google.com/file/d/1q1TtT-E8NF7x801iNdjcTwiPP4zfRe_9/view?usp=sharing)
The description says it all.

**Comment by aehmttw** [comment]
Please read the text inside of the tank editor. Tread color is set to team color if there is a team.

**Comment by ghostlypi** [comment]
The point is that the UI indicates that turret colour and tread colour are locked together, despite the fact that the UI indicates otherwise. If this is expected behavior, the UI should be modified to indicate that these two are the same. An edit to tread colour should **NOT** change team colour as this would change the colour of the treads of all Tanks on the team.
