### ISSUE TITLE
Feature request - FPS cap

### ISSUE THREAD

**Issue by 501Ghost** [aehmttw/Tanks#26]
Hello, 

I am enjoying Tanks The Crusades. I would like to have an option to limit my frames per second to 30 or 60. I haven't found this option in the game and I hope it's not something that I overlooked.

**Comment by 501Ghost** [comment]
Thank you very much. I must have missed it, then. Have a good day.

**Comment by aehmttw** [comment]
Glad that helped! Feel free to ask if you have any other questions!
