### ISSUE TITLE
Blocked site

### ISSUE THREAD

**Issue by laparda14** [aehmttw/Tanks#37]
The website that you provided is blocked from securly.

**Comment by aehmttw** [comment]
> The website that you provided is blocked from securly.

Which website?

**Comment by pythonmcpi** [comment]
Securly is a piece of "legitimate spyware", meaning it is marketed as a piece of legitimate software but performs actions consistent with spyware. I recommend uninstalling it if you can, and using a different device if you are unable to.

Also note that Tanks does not support running on ChromeOS.

**Comment by laparda14** [comment]
The blocked site is: https://aehmttw.itch.io/tanks

**Comment by pythonmcpi** [comment]
There is nothing we can do about a piece of malware that blocks a particular site. Try accessing the itch.io page using a different device.

**Comment by aehmttw** [comment]
You can also download the jar from the onedrive link in the readme or from the github actions builds
