### ISSUE TITLE
Modding Support

### ISSUE THREAD

**Issue by 1ue999** [aehmttw/Tanks#41]
Hello, this is a really good game, but i would like modding support (a game which did it perfectly: [https://github.com/anuken/mindustry](url)).
I would LOVE it if you added mods, so that we can add: custom bullets (like an explosive arc bullet), and mod the game in general. idk how hard that would be, if it isnt too hard, please implement it (also new soundtrack is perfect :D)

**Comment by 1ue999** [comment]
hmm the link dosnt work
you can just copy it ig

**Comment by aehmttw** [comment]
You should check this out: https://www.youtube.com/watch?v=m42QqTErYnY
